{% set version = "2.9.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-poppr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/poppr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/poppr/poppr_{{ version }}.tar.gz
  sha256: df558152c12bb8581835da5891421c555f6fc92ddc21236597a60fd65caca9ab

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-ade4                     # [build_platform != target_platform]
    - r-adegenet >=2.0.0         # [build_platform != target_platform]
    - r-ape >=3.1_1              # [build_platform != target_platform]
    - r-boot                     # [build_platform != target_platform]
    - r-dplyr >=0.4              # [build_platform != target_platform]
    - r-ggplot2                  # [build_platform != target_platform]
    - r-igraph >=1.0.0           # [build_platform != target_platform]
    - r-magrittr                 # [build_platform != target_platform]
    - r-pegas                    # [build_platform != target_platform]
    - r-polysat                  # [build_platform != target_platform]
    - r-progressr                # [build_platform != target_platform]
    - r-rlang                    # [build_platform != target_platform]
    - r-shiny                    # [build_platform != target_platform]
    - r-vegan                    # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
    - llvm-openmp                # [osx]
    - libgomp                    # [linux]
  host:
    - r-base
    - r-ade4
    - r-adegenet >=2.0.0
    - r-ape >=3.1_1
    - r-boot
    - r-dplyr >=0.4
    - r-ggplot2
    - r-igraph >=1.0.0
    - r-magrittr
    - r-pegas
    - r-polysat
    - r-progressr
    - r-rlang
    - r-shiny
    - r-vegan
    - llvm-openmp                # [osx]
  run:
    - r-base
    - r-ade4
    - r-adegenet >=2.0.0
    - r-ape >=3.1_1
    - r-boot
    - r-dplyr >=0.4
    - r-ggplot2
    - r-igraph >=1.0.0
    - r-magrittr
    - r-pegas
    - r-polysat
    - r-progressr
    - r-rlang
    - r-shiny
    - r-vegan
    - llvm-openmp                # [osx]

test:
  commands:
    - $R -e "library('poppr')"           # [not win]
    - "\"%R%\" -e \"library('poppr')\""  # [win]

about:
  home: https://github.com/grunwaldlab/poppr
  doc_url: https://grunwaldlab.github.io/Population_Genetics_in_R/
  license: GPL-2.0-or-later
  summary: Population genetic analyses for hierarchical analysis of partially clonal populations built upon the architecture of the 'adegenet' package. Originally described in Kamvar, Tabima, and Grünwald (2014) <doi:10.7717/peerj.281> with version 2.0 described in Kamvar, Brooks, and Grünwald (2015) <doi:10.3389/fgene.2015.00208>.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
