{% set version = "2.9.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-poppr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/poppr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/poppr/poppr_{{ version }}.tar.gz
  sha256: a6236bd7749339837763ffd3cad5c5fd02b0f03f0bf4dbb91e41b8cdb69ec656

build:
  merge_build_host: true  # [win]
  skip: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - llvm-openmp                # [osx]
    - libgomp                    # [linux]
    - r-base
    - r-ade4
    - r-adegenet >=2.0.0
    - r-ape >=3.1_1
    - r-boot
    - r-dplyr >=0.4
    - r-ggplot2
    - r-igraph >=1.0.0
    - r-magrittr
    - r-pegas
    - r-phangorn
    - r-polysat
    - r-progressr
    - r-rlang
    - r-shiny
    - r-vegan
  run:
    - r-base
    - {{ native }}gcc-libs       # [win]
    - r-ade4
    - r-adegenet >=2.0.0
    - r-ape >=3.1_1
    - r-boot
    - r-dplyr >=0.4
    - r-ggplot2
    - r-igraph >=1.0.0
    - r-magrittr
    - r-pegas
    - r-phangorn
    - r-polysat
    - r-progressr
    - r-rlang
    - r-shiny
    - r-vegan

test:
  commands:
    - $R -e "library('poppr')"           # [not win]
    - "\"%R%\" -e \"library('poppr')\""  # [win]

about:
  home: https://github.com/grunwaldlab/poppr
  doc_url: https://grunwaldlab.github.io/Population_Genetics_in_R/
  license: GPL-2.0-or-later
  summary: Population genetic analyses for hierarchical analysis of partially clonal populations built upon the architecture of the 'adegenet' package. Originally described in Kamvar, Tabima, and Grünwald (2014) <doi:10.7717/peerj.281> with version 2.0 described in Kamvar, Brooks, and Grünwald (2015) <doi:10.3389/fgene.2015.00208>.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
